version: "3.7"

services:

  nginx:
    container_name: schoolball_nginx
    build:
      context: ./docker/nginx
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/app
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    networks:
      - "backend_network"

  php-fpm:
    container_name: schoolball_php-fpm
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/var/www/app
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - "backend_network"

  mysql:
    container_name: schoolball_mysql
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: schoolball
      MYSQL_USER: schoolball
      MYSQL_PASSWORD: schoolball
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - "backend_network"

networks:
  backend_network:
    driver: bridge
